const overlay = document.createElement('div');
overlay.style.position = 'fixed';
overlay.style.top = '10px';
overlay.style.right = '10px';
overlay.style.background = 'white';
overlay.style.border = '1px solid black';
overlay.style.padding = '10px';
overlay.style.zIndex = 1000;
overlay.textContent = "Overlay is working!";
document.body.appendChild(overlay);
